classDiagram

class ARGUS{

+analyze()

+aggregate()

+reason()

+validate()

}

class CompanyTool

class FinanceTool

class NewsTool

class RiskTool

class CompetitorTool

class PromptBuilder

class ConfidenceEngine

class Validator

ARGUS --> CompanyTool

ARGUS --> FinanceTool

ARGUS --> NewsTool

ARGUS --> RiskTool

ARGUS --> CompetitorTool

ARGUS --> PromptBuilder

ARGUS --> Validator

ARGUS --> ConfidenceEngine